"""
ff_explorer.api.main
=====================
Combined ASGI application: REST routes + MCP at ``/mcp``.

This is the **single runnable entry point** for the access layer.  It
composes the FastAPI REST app (``rest.app``) and the FastMCP ASGI
app (``mcp_server.mcp_app``) into one ``FastAPI`` instance served by a
single uvicorn process.

Architecture
------------
  rest.app           — the FastAPI REST app (routes: /health, /entries,
                       /metadata, /listing, /remove, /compress)
  mcp_server.mcp_app — the FastMCP Starlette HTTP app (Streamable HTTP at /mcp)
  app                — this module's combined app:
                         • REST routes included directly (exception handlers
                           live in the route functions and carry through)
                         • mcp_app mounted at root so /mcp is reachable
                         • MCP session-manager lifespan forwarded via
                           ``lifespan=mcp_app.lifespan``

Composition strategy (FFX-B03)
-------------------------------
The earlier implementation appended raw ``mcp_app.routes`` and
``_rest_app.routes`` into a fresh ``FastAPI``.  That splice copies route
objects but loses the REST app's middleware stack and exception handlers
(which live on the *app*, not in ``.routes``).

The fixed composition:

1. ``lifespan=mcp_app.lifespan`` — forwards the FastMCP session-manager
   startup/shutdown to the combined app (required by FastMCP).
2. ``app.router.routes.append(route)`` for each ``APIRoute`` from
   ``_rest_app.routes`` — copies only the real API routes, not the
   auto-generated OpenAPI infrastructure routes (avoids duplicates).
   Exception mapping (EmptySeedError/ValueError→422, FileNotFoundError→404)
   is performed inside each route function, so it carries without any
   app-level handler forwarding.
3. ``app.mount('', mcp_app)`` — mounts the MCP Starlette sub-app at the
   root so requests to ``/mcp`` reach it.  The sub-app's own lifespan is
   NOT called for mounted sub-apps; the top-level ``lifespan=`` handles it.

Bind policy (FFX-B06)
----------------------
``run_server`` defaults to ``host="127.0.0.1"`` (loopback).  Binding all
interfaces requires an explicit opt-in:

  • CLI flag:  ``ff-explorer-api --host 0.0.0.0``
  • Env var:   ``FFE_BIND_ALL=1 ff-explorer-api``

When ``FFE_BIND_ALL=1`` is set and no ``--host`` flag is given, the server
binds ``0.0.0.0``.  An explicit ``--host`` value always takes precedence
over the environment variable.  See ``api/README-access.md`` for details.

Run commands
------------
HTTP server (REST + MCP Streamable HTTP)::

    ff-explorer-api                          # loopback (default)
    ff-explorer-api --host 0.0.0.0           # all interfaces (explicit opt-in)
    FFE_BIND_ALL=1 ff-explorer-api           # all interfaces via env var

    uvicorn ff_explorer.api.main:app --host 127.0.0.1 --port 8000

stdio MCP client::

    ff-explorer-mcp

Endpoints after startup
-----------------------
REST:
  GET  http://localhost:8000/health
  POST http://localhost:8000/entries
  POST http://localhost:8000/metadata
  POST http://localhost:8000/listing
  POST http://localhost:8000/remove
  POST http://localhost:8000/compress

MCP (Streamable HTTP):
  http://localhost:8000/mcp

Interactive docs (FastAPI auto-generated):
  http://localhost:8000/docs
  http://localhost:8000/redoc
"""
from __future__ import annotations

import argparse
import os

import uvicorn
from fastapi import FastAPI
from fastapi.routing import APIRoute

from ff_explorer import __version__
from ff_explorer.api.mcp_server import mcp_app
from ff_explorer.api.rest import app as _rest_app

# ---------------------------------------------------------------------------
# Combine REST routes + MCP sub-app in one ASGI app (FFX-B03 fixed).
#
# lifespan=mcp_app.lifespan  — REQUIRED: starts the FastMCP session manager.
# include only APIRoute instances — avoids duplicating OpenAPI infra routes.
# mount('', mcp_app)         — /mcp requests reach the MCP Starlette app.
# ---------------------------------------------------------------------------

app = FastAPI(
    title="FF-Explorer (REST + MCP)",
    version=__version__,
    description=(
        "Combined REST + MCP access layer for the FF-Explorer package.  "
        "REST routes are served directly; MCP (Streamable HTTP) is at /mcp.  "
        "Destructive routes (remove, compress) default to dry-run preview mode."
    ),
    lifespan=mcp_app.lifespan,  # REQUIRED: starts the MCP session manager
)

# Copy only the real API routes from the REST app (skip /openapi.json, /docs,
# /redoc — those are auto-generated by FastAPI and would cause duplicates).
for _route in _rest_app.routes:
    if isinstance(_route, APIRoute):
        app.router.routes.append(_route)

# Mount the MCP Starlette sub-app at the root so /mcp is reachable.
app.mount("", mcp_app)


# ---------------------------------------------------------------------------
# Host-resolution helper — testable without binding a real socket (FFX-B06).
# ---------------------------------------------------------------------------

def _resolve_host(host_arg: str | None) -> str:
    """Return the bind host given an explicit CLI argument and the environment.

    Priority:
      1. ``host_arg`` if not ``None`` (explicit ``--host`` flag wins).
      2. ``"0.0.0.0"`` when ``FFE_BIND_ALL=1`` is set in the environment.
      3. ``"127.0.0.1"`` (secure loopback default).
    """
    if host_arg is not None:
        return host_arg
    if os.environ.get("FFE_BIND_ALL") == "1":
        return "0.0.0.0"
    return "127.0.0.1"


# ---------------------------------------------------------------------------
# Console-script entry point (ff-explorer-api)
# ---------------------------------------------------------------------------

def run_server() -> None:  # pragma: no cover
    """Start the uvicorn server.

    Invoked by the ``ff-explorer-api`` console script.  Parses ``--host``
    and ``--port`` from ``sys.argv``; honours the ``FFE_BIND_ALL`` env var
    for the all-interfaces opt-in (see module docstring).
    """
    parser = argparse.ArgumentParser(
        prog="ff-explorer-api",
        description="FF-Explorer REST + MCP HTTP server.",
    )
    parser.add_argument(
        "--host",
        default=None,
        metavar="HOST",
        help=(
            "Bind address (default: 127.0.0.1).  "
            "Pass 0.0.0.0 or set FFE_BIND_ALL=1 to bind all interfaces."
        ),
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8000,
        metavar="PORT",
        help="TCP port to listen on (default: 8000).",
    )
    args = parser.parse_args()
    host = _resolve_host(args.host)
    uvicorn.run(app, host=host, port=args.port)


if __name__ == "__main__":  # pragma: no cover
    run_server()
