# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for FFExplorer — FF Explorer GUI (PySide6)
# Generated by the packaging agent (repo-enhancer) on 2026-06-12.
#
# PyInstaller version: 6.20.0
# Python target:       3.13.x  (3.13.13 installed; project requires >=3.11)
# Platform:            Windows (primary); see build_posix.sh for Linux/macOS
#
# SPECPATH resolution note
# ------------------------
# PyInstaller sets SPECPATH to the spec's directory (packaging/), NOT the repo
# root.  REPO_ROOT is resolved as Path(SPECPATH).parent so all Analysis paths
# are anchored to the repo root regardless of the working directory at build
# time.
#
# Data bundling
# -------------
# ff_explorer/gui/_resources.py implements resource_path(relative):
#   - Frozen (PyInstaller): base = Path(sys._MEIPASS)
#   - Source:               base = Path(__file__).parent.parent.parent  (repo root)
# logo_path calls resource_path("Logo FFE.png")  → dest "." (bundle root)
#
# send2trash (critical hidden import)
# ------------------------------------
# ff_explorer/core.py imports send2trash at module scope (try/except ImportError).
# PyInstaller does not detect it through the try/except guard so it MUST be
# listed in hiddenimports or the frozen exe will silently fall back to the
# os.remove/shutil.rmtree path even when send2trash is installed at build time.
#
# API/server exclusions
# ---------------------
# The GUI bundle does NOT include FastMCP / FastAPI / uvicorn.  Those are
# excluded explicitly; they live in ff_explorer/api/ which is NOT imported
# by the GUI entry point, but belt-and-braces exclusion prevents transitive
# pulls.

import sys
from pathlib import Path

# Repo root — one level above the spec file (packaging/ directory)
REPO_ROOT = str(Path(SPECPATH).parent)

block_cipher = None

a = Analysis(
    # Entry point: ff_explorer/gui/app.py  (gui-script: ff-explorer-gui)
    [str(Path(REPO_ROOT) / 'ff_explorer' / 'gui' / 'app.py')],
    pathex=[REPO_ROOT],
    binaries=[],
    datas=[
        # Application logo — resolved at runtime via resource_path("Logo FFE.png")
        # dest "." = bundle root so sys._MEIPASS / "Logo FFE.png" resolves correctly
        (str(Path(REPO_ROOT) / 'Logo FFE.png'), '.'),
    ],
    hiddenimports=[
        # PySide6: PyInstaller 6.x ships PySide6 hooks that collect Qt plugins
        # automatically.  These explicit entries guard against edge cases where
        # the platform plugin is not collected by the hook alone.
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        # send2trash: imported via try/except in ff_explorer.core — PyInstaller
        # cannot see through the guard, so must be declared explicitly.
        'send2trash',
        'send2trash.win',
    ],
    hookspath=[],
    hooksconfig={
        # Instruct the bundled PySide6 hook to collect the platform plugin
        # (qwindows.dll on Windows) and Qt image-format plugins (needed to
        # load Logo FFE.png at runtime via QPixmap).
        'PySide6': {
            'collect_all': False,
        },
    },
    runtime_hooks=[],
    excludes=[
        # Exclude the access-layer stack — not needed in the GUI bundle.
        'fastmcp',
        'fastapi',
        'uvicorn',
        'starlette',
        'httpx',
        'anyio',
        # Exclude server-only parts of this package.
        'ff_explorer.api',
    ],
    noarchive=False,
    cipher=block_cipher,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,      # one-dir mode: binaries go into COLLECT
    name='FFExplorer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,              # --windowed / --noconsole: no console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # icon: uncomment after running scripts/png_to_ico.py to produce Logo FFE.ico
    icon=str(Path(REPO_ROOT) / 'Logo FFE.ico'),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='FFExplorer',          # output folder: packaging/bin/FFExplorer/
)
